### PR TITLE
Add experimental support for automatic reconnection

### LINKED ISSUE #47: Include automatic reconnection (very configurable!)
See discussion in https://github.com/AlCalzone/node-tradfri-client/issues/44#issuecomment-372255548

### PR DESCRIPTION
**Pull request by AlCalzone**
Fixes #47

### CODE REVIEW

**Comment by AlCalzone** [comment]
@neophob Do you wanna give this a try?

**Comment by neophob** [comment]
Great stuff @AlCalzone! Here's a first feedback:

I used this reconnect settings:

```
  const libraryOptions = {
    watchConnection: {
      pingInterval: 2000,
      failedPingCountUntilOffline: 3,
    }
  };
```

and added these 3 new callbacks:

```
      .on('gateway offline', this.tradfriGatewayOffline.bind(this))
      .on('connection lost', this.tradfriConnectionLost.bind(this))
      .on('connection alive', this.tradfriConnectionAlive.bind(this))
```

I rebooted the gateway, and got all 3 callbacks (as expected) - in the connection alive callback I start the observer devices again. :thumbsup: great job!



Questions:

- does it make sense that the library automatically restarts resource observing? (remove old observers and register new ones - depending on what resources were obseved)

**Comment by AlCalzone** [comment]
> does it make sense that the library automatically restarts resource observing? (remove old observers and register new ones - depending on what resources were obseved)

Absolutely! I also want to include retrying of the initial connection (assuming the user has already authenticated).

**Comment by neophob** [comment]
> Absolutely! I also want to include retrying of the initial connection (assuming the user has already authenticated).

Wow, can you read minds - i just was testing that case when the gateway is initially not available ;)

**Comment by AlCalzone** [comment]
released in v0.12.0

**Comment by AlCalzone** [comment]
Retrying of the initial connection is live in v0.12.1

**Pull request merged**
