### PR TITLE
Defer the promises of observeDevices/observeGroups until the devices/groups are received

### LINKED ISSUE #6: Question about initialisation
Currently I am setting up to use the library by listening on all all six possible events and then calling `observeDevices()` and `observeGroupsAndScenes()` in a `Promise.all()`.  The gateway responds by emitting an event for each device, group and scene which I use to initialise my data structure.  However the promise resolves immediately, returning the `TradfriClient` class.

My question is: Is there any way to know when the initialisation phase is over?  For example, is there a way to find in advance the number of devices, groups and scenes to expect?  Or could there be an event triggered to indicate that initialisation is finished?  Or perhaps could the resolution of the promises returned by `observeDevices()` and `observeGroupsAndScenes()` be deferred until after the initialisation is complete?

### PR DESCRIPTION
**Pull request by AlCalzone**
Resolves #6 

- [x] defer `observeDevices`
- [x] defer `observeGroups`
- [x] fix broken tests for `observeDevices`
- [ ] fix broken tests for `observeGroups`

### CODE REVIEW

**Comment by CliffS** [comment]
I'm getting:

```/home/cliff/src/git/node-tradfri-client/build/tradfri-client.js:190
                            if (newKeys.each(k => k in this.devices)) {
                                        ^

TypeError: newKeys.each is not a function
    at PendingRequest.handleResponse [as callback] (/home/cliff/src/git/node-tradfri-client/build/tradfri-client.js:190:41)
    at Function.onMessage (/home/cliff/src/git/node-tradfri-client/node_modules/node-coap-client/build/CoapClient.js:511:33)
    at SocketWrapper.emit (events.js:159:13)
    at SocketWrapper.socket.on (/home/cliff/src/git/node-tradfri-client/node_modules/node-coap-client/build/lib/SocketWrapper.js:12:18)
    at Socket.emit (events.js:159:13)
    at Socket.udp_onMessage (/home/cliff/src/git/node-tradfri-client/node_modules/node-dtls-client/build/dtls.js:204:34)
    at Socket.emit (events.js:159:13)
    at UDP.onMessage (dgram.js:658:8)
```

**Comment by AlCalzone** [comment]
yup, I forgot a type assertion, so TS didn't complain that `each` is not a function. It should have been `every`.

**Comment by AlCalzone** [comment]
tests for `observeGroupsAndScenes` will have to wait

**Comment by CliffS** [comment]
Getting the following warning on installation:

```
node-pre-gyp ERR! Tried to download(404): https://github.com/AlCalzone/node-aead-crypto/releases/download/v1.0.2/node-v59-linux-x64.tar.gz 
```

**Comment by AlCalzone** [comment]
Thats because I'm not precompiling binaries for Node 9.
=> https://github.com/AlCalzone/node-aead-crypto/issues/2

**Pull request merged**
